<h1>Building an ML model</h1>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [3]:
from google.colab import files
files=files.upload()
df = pd.read_csv('ohe_data.csv')

Saving ohe_data.csv to ohe_data.csv


In [4]:

df.shape

(7120, 108)

In [5]:

df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
0                    0                           1                    0   
1                    0                           1                    0   
2                    0                           1                    0   
3                    0                           1                    0   
4                    1                           1                    0   

   location_Sarjapur  Road  location_Electronic City  location_Marathahalli  \
0                        0                         0                      0   
1                        0                         0                      0   
2                        0                         0                      0   
3                        0                         0                      0   
4                        0                         0                      0   

   location_Raja Rajeshwari Nagar  location_Haralur Road  \
0                               0                      0   
1                               0                      0   
2                               0                      0   
3                               0                      0   
4                               0                      0   

   location_Hennur Road  location_Bannerghatta Road  location_Uttarahalli  \
0                     0                           0                     0   
1                     0                           0                     0   
2                     0                           0                     0   
3                     0                           0                     0   
4                     0                           0                     0   

   location_Thanisandra  location_Electronic City Phase II  location_Hebbal  \
0                     0                                  0                0   
1                     0                                  0                0   
2                     0                                  0                0   
3                     0                                  0                0   
4                     0                                  0                0   

   location_Yelahanka  location_7th Phase JP Nagar  location_Kanakpura Road  \
0                   0                            0                        0   
1                   0                            0                        0   
2                   0                            0                        0   
3                   0                            0                        0   
4                   0                            0                        0   

   location_KR Puram  location_Sarjapur  location_Rajaji Nagar  \
0                  0                  0                      0   
1                  0                  0                      0   
2                  0                  0                      0   
3                  0                  0                      0   
4                  0                  0                      0   

   location_Bellandur  location_Kasavanhalli  location_Begur Road  \
0                   0                      0                    0   
1               

In [6]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
0                    0                           1                    0   
1                    0                           1                    0   
2                    0                           1                    0   
3                    0                           1                    0   
4                    1                           1                    0   

   location_Sarjapur  Road  location_Electronic City  location_Marathahalli  \
0                        0                         0                      0   
1                        0                         0                      0   
2                        0                         0                      0   
3                        0                         0                      0   
4                        0                         0                      0   

   location_Raja Rajeshwari Nagar  location_Haralur Road  \
0                               0                      0   
1                               0                      0   
2                               0                      0   
3                               0                      0   
4                               0                      0   

   location_Hennur Road  location_Bannerghatta Road  location_Uttarahalli  \
0                     0                           0                     0   
1                     0                           0                     0   
2                     0                           0                     0   
3                     0                           0                     0   
4                     0                           0                     0   

   location_Thanisandra  location_Electronic City Phase II  location_Hebbal  \
0                     0                                  0                0   
1                     0                                  0                0   
2                     0                                  0                0   
3                     0                                  0                0   
4                     0                                  0                0   

   location_Yelahanka  location_7th Phase JP Nagar  location_Kanakpura Road  \
0                   0                            0                        0   
1                   0                            0                        0   
2                   0                            0                        0   
3                   0                            0                        0   
4                   0                            0                        0   

   location_KR Puram  location_Sarjapur  location_Rajaji Nagar  \
0                  0                  0                      0   
1                  0                  0                      0   
2                  0                  0                      0   
3                  0                  0                      0   
4                  0                  0                      0   

   location_Bellandur  location_Kasavanhalli  location_Begur Road  \
0                   0                      0                    0   
1               

In [7]:
"""## Split Dataset in train and test"""
 
X = df.drop("price", axis=1)
y = df['price']
print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 51)
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


In [9]:
"""## Feature Scaling"""
 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train= sc.transform(X_train)
X_test = sc.transform(X_test)

In [10]:
"""## Machine Learning Model Training
 
## Linear Regression
"""
 
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
lr = LinearRegression()
lr_lasso = Lasso()
lr_ridge = Ridge()

In [11]:
def rmse(y_test, y_pred):
  return np.sqrt(mean_squared_error(y_test, y_pred))
 
lr.fit(X_train, y_train)
lr_score = lr.score(X_test, y_test) # with all num var 0.7842744111909903
lr_rmse = rmse(y_test, lr.predict(X_test))
lr_score, lr_rmse

(0.7903837092682255, 64.89843531105602)

In [12]:
# Lasso 
lr_lasso.fit(X_train, y_train)
lr_lasso_score=lr_lasso.score(X_test, y_test) # with balcony 0.5162364637824872
lr_lasso_rmse = rmse(y_test, lr_lasso.predict(X_test))
lr_lasso_score, lr_lasso_rmse

(0.8036372973672521, 62.813242204691555)

In [16]:
"""## Support Vector Machine"""
 
from sklearn.svm import SVR
svr = SVR()
svr.fit(X_train,y_train)
svr_score=svr.score(X_test,y_test) # with 0.2630802200711362
svr_rmse = rmse(y_test, svr.predict(X_test))
svr_score, svr_rmse

(0.20638035840828173, 126.27806378079055)

In [13]:
"""## Random Forest Regressor"""
 
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(X_train,y_train)
rfr_score=rfr.score(X_test,y_test) # with 0.8863376025408044
rfr_rmse = rmse(y_test, rfr.predict(X_test))
rfr_score, rfr_rmse

(0.8934165866198863, 46.277141237623795)

In [14]:
"""## XGBoost"""
 
import xgboost
xgb_reg = xgboost.XGBRegressor()
xgb_reg.fit(X_train,y_train)
xgb_reg_score=xgb_reg.score(X_test,y_test) # with 0.8838865742273464
xgb_reg_rmse = rmse(y_test, xgb_reg.predict(X_test))
xgb_reg_score, xgb_reg_rmse

(0.8866071985706575, 47.73252984729787)

In [17]:
print(pd.DataFrame([{'Model': 'Linear Regression','Score':lr_score, "RMSE":lr_rmse},
              {'Model': 'Lasso','Score':lr_lasso_score, "RMSE":lr_lasso_rmse},
              {'Model': 'Support Vector Machine','Score':svr_score, "RMSE":svr_rmse},
              {'Model': 'Random Forest','Score':rfr_score, "RMSE":rfr_rmse},
              {'Model': 'XGBoost','Score':xgb_reg_score, "RMSE":xgb_reg_rmse}],
             columns=['Model','Score','RMSE']))

                    Model     Score        RMSE
0       Linear Regression  0.790384   64.898435
1                   Lasso  0.803637   62.813242
2  Support Vector Machine  0.206380  126.278064
3           Random Forest  0.893417   46.277141
4                 XGBoost  0.886607   47.732530


In [18]:
"""## Cross Validation"""
 
from sklearn.model_selection import KFold,cross_val_score
cvs = cross_val_score(xgb_reg, X_train,y_train, cv = 10)
cvs, cvs.mean() # 0.9845963377450353)

(array([0.98991766, 0.98632505, 0.99685279, 0.98296558, 0.97656955,
        0.99525125, 0.97360094, 0.94556716, 0.99408487, 0.98854857]),
 0.9829683423733027)

In [19]:
cvs_rfr = cross_val_score(rfr, X_train,y_train, cv = 10)
cvs_rfr, cvs_rfr.mean() # 0.9652425691235843)

(array([0.991548  , 0.95684631, 0.9977923 , 0.97422004, 0.96530165,
        0.93147588, 0.94293705, 0.90864149, 0.99675013, 0.98948002]),
 0.9654992875911675)

In [20]:
from sklearn.model_selection import cross_val_score
cvs_rfr2 = cross_val_score(RandomForestRegressor(), X_train,y_train, cv = 10)
cvs_rfr2, cvs_rfr2.mean() # 0.9652425691235843)

(array([0.99154604, 0.96823157, 0.99734878, 0.96817488, 0.9680747 ,
        0.9477437 , 0.92612231, 0.91591544, 0.99606147, 0.98811826]),
 0.9667337155042659)

In [21]:
"""# Hyper Parmeter Tuning"""
 
from sklearn.model_selection import GridSearchCV
from xgboost.sklearn import XGBRegressor

In [22]:
xgb1 = XGBRegressor()
parameters = {'learning_rate': [0.1,0.03, 0.05, 0.07], #so called `eta` value, # [default=0.3] Analogous to learning rate in GBM
              'min_child_weight': [1,3,5], #[default=1] Defines the minimum sum of weights of all observations required in a child.
              'max_depth': [4, 6, 8], #[default=6] The maximum depth of a tree,
              'gamma':[0,0.1,0.001,0.2], #Gamma specifies the minimum loss reduction required to make a split.
              'subsample': [0.7,1,1.5], #Denotes the fraction of observations to be randomly samples for each tree.
              'colsample_bytree': [0.7,1,1.5], #Denotes the fraction of columns to be randomly samples for each tree.
              'objective':['reg:linear'], #This defines the loss function to be minimized.
 
              'n_estimators': [100,300,500]}

In [23]:
xgb_grid = GridSearchCV(xgb1,
                        parameters,
                        cv = 2,
                        n_jobs = -1,
                        verbose=True)

In [28]:
xgb_tune = xgb_grid.estimator
 
xgb_tune.fit(X_train,y_train) # 0.9117591385438816
xgb_tune.score(X_test,y_test)

0.8866071985706575

In [29]:
cvs = cross_val_score(xgb_tune, X_train,y_train, cv = 10)
cvs, cvs.mean() #  0.9645582338461773

(array([0.98991766, 0.98632505, 0.99685279, 0.98296558, 0.97656955,
        0.99525125, 0.97360094, 0.94556716, 0.99408487, 0.98854857]),
 0.9829683423733027)

In [30]:
[i/10.0 for i in range(1,6)]
 
xgb_grid.estimator

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [32]:
cvs = cross_val_score(xgb_tune2, X_train,y_train, cv = 5)
cvs, cvs.mean() #  0.9706000326331659'''
 

[15:02:38] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.


/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_scorer.py", line 117, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_scorer.py", line 444, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/base.py", line 722, in score
    y_pred = self.predict(X)
  File "/usr/local/lib/python3.9/dist-packages/xgboost/sklearn.py", line 1114, in predict
    predts = self.get_booster().inplace_predict(
  File "/usr/local/lib/python3.9/dist-packages/xgboost/core.py", line 2292, in inplace_predict
    _check_call(
  File "/usr/local/lib/python3.9/dist-packages/xgboost/core.py", line 279, in _check_call
    raise X

[15:02:40] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.


/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_scorer.py", line 117, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_scorer.py", line 444, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/base.py", line 722, in score
    y_pred = self.predict(X)
  File "/usr/local/lib/python3.9/dist-packages/xgboost/sklearn.py", line 1114, in predict
    predts = self.get_booster().inplace_predict(
  File "/usr/local/lib/python3.9/dist-packages/xgboost/core.py", line 2292, in inplace_predict
    _check_call(
  File "/usr/local/lib/python3.9/dist-packages/xgboost/core.py", line 279, in _check_call
    raise X

[15:02:41] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.


/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_scorer.py", line 117, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_scorer.py", line 444, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/base.py", line 722, in score
    y_pred = self.predict(X)
  File "/usr/local/lib/python3.9/dist-packages/xgboost/sklearn.py", line 1114, in predict
    predts = self.get_booster().inplace_predict(
  File "/usr/local/lib/python3.9/dist-packages/xgboost/core.py", line 2292, in inplace_predict
    _check_call(
  File "/usr/local/lib/python3.9/dist-packages/xgboost/core.py", line 279, in _check_call
    raise X

[15:02:43] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.


/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_scorer.py", line 117, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_scorer.py", line 444, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/base.py", line 722, in score
    y_pred = self.predict(X)
  File "/usr/local/lib/python3.9/dist-packages/xgboost/sklearn.py", line 1114, in predict
    predts = self.get_booster().inplace_predict(
  File "/usr/local/lib/python3.9/dist-packages/xgboost/core.py", line 2292, in inplace_predict
    _check_call(
  File "/usr/local/lib/python3.9/dist-packages/xgboost/core.py", line 279, in _check_call
    raise X

[15:02:44] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.


/usr/local/lib/python3.9/dist-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_scorer.py", line 117, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_scorer.py", line 444, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sklearn/base.py", line 722, in score
    y_pred = self.predict(X)
  File "/usr/local/lib/python3.9/dist-packages/xgboost/sklearn.py", line 1114, in predict
    predts = self.get_booster().inplace_predict(
  File "/usr/local/lib/python3.9/dist-packages/xgboost/core.py", line 2292, in inplace_predict
    _check_call(
  File "/usr/local/lib/python3.9/dist-packages/xgboost/core.py", line 279, in _check_call
    raise X

(array([nan, nan, nan, nan, nan]), nan)

In [33]:
"""## Test Model"""
 
list(X.columns)
 
# it help to get predicted value of hosue  by providing features value 
def predict_house_price(model,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_type,availability,location):
 
  x =np.zeros(len(X.columns)) # create zero numpy array, len = 107 as input value for model
 
  # adding feature's value accorind to their column index
  x[0]=bath
  x[1]=balcony
  x[2]=total_sqft_int
  x[3]=bhk
  x[4]=price_per_sqft
 
  if "availability"=="Ready To Move":
    x[8]=1
 
  if 'area_type'+area_type in X.columns:
    area_type_index = np.where(X.columns=="area_type"+area_type)[0][0]
    x[area_type_index] =1
 
    #print(area_type_index)
 
  if 'location_'+location in X.columns:
    loc_index = np.where(X.columns=="location_"+location)[0][0]
    x[loc_index] =1
 
    #print(loc_index)
 
  #print(x)
 
  # feature scaling
  x = sc.transform([x])[0] # give 2d np array for feature scaling and get 1d scaled np array
  #print(x)
 
  return model.predict([x])[0] # return the predicted value by train XGBoost model

In [34]:
predict_house_price(model=xgb_tune2, bath=3,balcony=2,total_sqft_int=1672,bhk=3,price_per_sqft=8971.291866,area_type="Plot  Area",availability="Ready To Move",location="Devarabeesana Halli")

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


146.30998

In [35]:
##test sample
#area_type  availability    location    bath    balcony price   total_sqft_int  bhk price_per_sqft
#2  Super built-up Area Ready To Move   Devarabeesana Halli 3.0 2.0 150.0   1750.0  3   8571.428571
 
predict_house_price(model=xgb_tune2, bath=3,balcony=2,total_sqft_int=1750,bhk=3,price_per_sqft=8571.428571,area_type="Super built-up",availability="Ready To Move",location="Devarabeesana Halli")

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


146.11647

In [36]:
"""# Save model & load model"""
 
import joblib
# save model
joblib.dump(xgb_tune2, 'bangalore_house_price_prediction_model.pkl')
joblib.dump(rfr, 'bangalore_house_price_prediction_rfr_model.pkl')

['bangalore_house_price_prediction_rfr_model.pkl']

In [37]:
# load model
bangalore_house_price_prediction_model = joblib.load("bangalore_house_price_prediction_model.pkl")

In [38]:
# predict house price
predict_house_price(bangalore_house_price_prediction_model,bath=3,balcony=3,total_sqft_int=150,bhk=3,price_per_sqft=8514.285714,area_type="Built-up Area",availability="Ready To Move",location="Devarabeesana Halli")


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


67.8374